### ISSUE TITLE
.xacro to .urdf

### ISSUE THREAD

**Issue by kavikode** [gkjohnson/xacro-parser#38]
How do you convert .xacro to .urdf within javascript please?

**Comment by gkjohnson** [comment]
I cannot volunteer my time to complete your project for you. The README documents how to use this project which should be enough to solve your problem. Please put some effort into your question as I have asked before and include what you have tried that does not work or what is unclear in the README so it can be updated. If you are unwilling to do that then I will not be able to help with these questions anymore.

**Comment by kavikode** [comment]
thank you for your response. It was unclear from the readme file of how to display the model of .xacro like your urdf-loader in the viewer. If you can please update the readme of what you do after you have parsed so that it is loaded for viewing, it will be helpful for others as well. Seriously, I'd just require direction and not the actual code itself. Additionally, I'm trying to prevent from a lot of trial and error due to the tedious task of typing through voice because of my physical disability. I am truly trying my best and advance as much as possible. I truly appreciate your understanding.

**Comment by gkjohnson** [comment]
I understand. Sorry to come across as terse before but I urge you to explain why it might be difficult for you to contribute when someone requests something of you otherwise it looks as though you are simply ignoring people and asking for more. I try rely on other people to help make changes and fixes when I can because otherwise it becomes too much of a burden for me to address every issue in my (and other peoples) code bases.

I agree it may be useful for others to show how to convert xacro to urdf to three.js. It may be a bit before I have time to sit down and recall how to do that exactly but the short of it is that you process the xacro file, convert it to a string, and then pass it to the URDFLoader parse function. You may have to update the working path for URDFLoader so it knows where to load meshes from, though.

If I add docs it will likely be in the `urdf-loaders` project repo to show how to use this package in conjunction with urdf loader.
