### ISSUE TITLE
Implementation for getFileContents(path)

### ISSUE THREAD

**Issue by cagucor** [gkjohnson/xacro-parser#47]
I am planning to write an implementation for this, but I am curious if there are any requirements to submit a pull request. What comes to mind is Node.js vs Browser requirements as I know that currently it supports both. 

I plan to implement it browser side where a user uploads a zip file and then it gets parsed. For this use case, I can extract the file paths relative to the ROS package and store it as part of a file object. The path attribute could then be used to iterate through the stored files until a matching one is found.

I was wondering if:

- There is a blueprint or some notes for how this function should be implemented
- What the scope for the function should be (different for Node vs browser)

Thanks

**Comment by gkjohnson** [comment]
Hi @cagucor! Sorry for taking a bit to respond it seems I wasn't getting notifications for this repo.

The `XacroLoader.js` file can be treated as a sort of reference implementation for parsing xacro in a browser via `fetch`. You can see the `getFileContents` implementation [here](https://github.com/gkjohnson/xacro-parser/blob/master/src/XacroLoader.js#L58-L75). It sounds like in your case you'd want to read the appropriate file from the user uploaded zip file rather than use fetch. For resolving package paths you can write a callback for the `find` function in the [rospackCommands](https://github.com/gkjohnson/xacro-parser#rospackcommands) option.

Regarding PRs I just ask that tests be written for new features and that you not commit the built UMD files so it's easier to look over the changes. What specifically were you planning to make a PR for?

Hopefully that covers what you're looking for -- let me know if you have any other questions!
