### ISSUE TITLE
xacro:if/unless ${not <variable>}

### ISSUE THREAD

**Issue by ndahn** [gkjohnson/xacro-parser#49]
I have found a [project](https://github.com/frankaemika/franka_ros/blob/kinetic-devel/franka_description/robots/panda_arm.xacro) (line 6) which uses `xacro:unless` together with `${not <variable>}`. This is clearly a degenerate case that could be easily resolved, but unfortunately it is still valid syntax. Right now the parser fails on this. I have tried some simple fixes, but it turns out that this problem runs quite deep. Replacing the `not ` part with an operator (e.g. `!`) inside `unpackParams` might be an option, but I'm unsure if this would encroach on existing valid syntax.

**Comment by gkjohnson** [comment]
Yeah I expected this kind of thing to crop up at some point. The core of the issue is that the original "Xacro" spec allows you to write arbitrary python for expressions which is inevitably difficult to be robust to in JS and is where `not` comes from. I'm happy to add more functionality to close the gap as issues come up if we can, though.

The `expr-eval` package is being used to safely evaluate expressions in [this file](https://github.com/gkjohnson/xacro-parser/blob/master/src/evaluateExpression.js) and it seems pretty impressively extensible. I'm wondering if just adding a `not` operator to the [unaryOperators](https://github.com/gkjohnson/xacro-parser/blob/master/src/evaluateExpression.js#L6-L10) object would just work here. Do you want to give that try to see if it works and make a PR with a test if it does? I think this is a good addition.

**Comment by gkjohnson** [comment]
Fixing this in #57. Looks like using `!` actually performed a factorial in expr-eval by default so I've fixed that to perform as expected now, as well.
